include:
  - board: nice_nano@2.0.0
    shield: my_kb_main
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#    snippets: 
#      - studio-rpc-usb-uart
#      - zmk-usb-logging

  - board: nice_nano@2.0.0
    shield: my_kb_npad

  - board: xiao_ble
    shield: my_kb_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
#    snippets: 
#      - studio-rpc-usb-uart
#      - zmk-usb-logging

  - board: nice_nano@2.0.0
    shield: settings_reset

  - board: xiao_ble
    shield: settings_reset
